# Generated by Django 3.1.1 on 2020-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0003_auto_20201006_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=30)),
                ('last_name', models.CharField(default='Doe', max_length=30)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
