# Generated by Django 3.1.1 on 2020-10-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0007_auto_20201006_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Veteran', 'Veteran')]),
        ),
    ]
