# Generated by Django 3.1.1 on 2020-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0008_auto_20201006_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.CharField(choices=[('Ea', 'Easy'), ('Me', 'Medium'), ('Ha', 'Hard'), ('Ve', 'Veteran')], max_length=50),
        ),
    ]
